### ISSUE TITLE
Custom flavour extensions should be in the npm package

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1040]
And before trying to load an external `js` file with `--customFlavour`, it should be checked in the internal `extensions` directory.

So:
* `--customFlavour=WiktionaryFR` should load `WikitionaryFR.js` in this extensions directory.
* `--customFlavour=foobar` should load `foobar.js` in the current directory (from where `mwoffliner` is launched by the user).
* `--customFlavour=foobar.js` should load `foobar.js` in the current directory (from where `mwoffliner` is launched by the user).
* `--customFlavour=/foobar.js` should load `foobar.js` in the root directory directory

**Comment by LakmaNeha** [comment]
@kelson42 can I take up this issue?

**Comment by LakmaNeha** [comment]
@kelson42 can I work on this?

**Comment by kelson42** [comment]
@LakmaNeha yes

**Comment by LakmaNeha** [comment]
@kelson42  If I understand correctly, except for the absolute path case(4th one), we always search for the extension first in the extensions directory and then, If we don't find in the extensions directory, then we are going to search in the current directory. Is that prioritisation right? or shall we search in the current directory first and then search in extensions directory. IMO searching for the file, first in the current directory and If not found, search in extensions directory makes sense, as this is a custom option provided to developer, we should prioritise developer's relative path first rather than our extension's path. What do you think?

**Comment by kelson42** [comment]
@LakmaNeha You are right, local first.

**Comment by LakmaNeha** [comment]
@kelson42 Also, if we can't locate the file, we are going to abort throwing an error message right? which is something like `couldn't locate the file in the current directory or extensions directory. Try giving the absolute path for the file.`

Secondly, as this may lead to file name conflict, I think showing some message like
`Using customProcessor - /some/absolute_path/to/customFlavour` would be informative and helps in debugging if something is wrong. What do you think?

**Comment by kelson42** [comment]
@LakmaNeha yes

**Comment by MananJethwani** [comment]
@kelson42 is this issue still open?.....I would like to work on it
