### ISSUE TITLE
Does that make sense to try to reprod the stucks with local MediaWiki? (option 1)

### ISSUE THREAD

**Issue by midik** [openzim/mwoffliner#1098]
Related to #1043

(option 1)
The idea is to try to reprod these stucks by setting up local mediawiki and create few stub articles there. Then run mwoffliner against billions of these articles locally (means much faster) and then play by ear.
Btw, I tried with MW 1.31 using `action=visualeditor` and it's not so much fast as expected at least on my CPU, thus would be a bit better better to use REST API.

**Comment by kelson42** [comment]
@midik You can try to do so. I don't think we need to change anything in the MWoffliner code to do so, so feel free. But I'm not convinced about this approach because I don't think this is really going to be much faster than WPEN API. That said, assuming this fails in 3 days instead 6 days... you are not going to know more than what you have got in 6 days. The key problem for the moment is not the speed, it is that we don't even know how to better understand the pb.

**Comment by midik** [comment]
The aim is not only the speed but ability to attach the debugger and see what's going on there.
