### ISSUE TITLE
HTML Output Files Not Created?

### ISSUE THREAD

**Issue by c0nsumer** [openzim/mwoffliner#1169]
I'm trying to use mwoffliner to archive https://nuxx.net/w/ to static HTML files. I've got mwoffliner running, but it doesn't seem to be outputting HTML files; only the ZIM file.

Here's the command I'm using:
`~/node_modules/.bin/mwoffliner --mwUrl="https://nuxx.net/" --adminEmail=steve@nuxx.net --redis="redis://localhost:6379" --mwWikiPath="/w/" --customZimFavicon=favicon-32x32.png`

This results in a .zim file, but no HTML:
```
c0nsumer@li931-106:~$ ls
favicon-32x32.png  node_modules  out
c0nsumer@li931-106:~$ ls out
nuxx_en_all_2020-06.zim
c0nsumer@li931-106:~$
```

mwoffliner exits with a 0 and the resulting zim file looks good in Kiwix with all the content there, but what I'm really wanting is HTML/image/etc output.

**Comment by kelson42** [comment]
@c0nsumer You want to extract all the content on your filesystem?

**Comment by c0nsumer** [comment]
That's what I'd like. My goal is to replace my mediawiki (as an app that needs maintenance) with these static files. I no longer use Mediawiki for publishing content and I'm wishing to create a static online archive.

**Comment by c0nsumer** [comment]
Note: I'm going off the description of the project which says it can do that. I'm just not sure if I'm doing something wrong, or if there's a bug?

> MWoffliner is a tool for making a local offline HTML snapshot of any online Mediawiki instance. It goes through all articles (or a selection if specified) and writes the HTML/images to a local directory. It has mainly been tested against Wikimedia projects like Wikipedia, Wiktionary, ... But it should also work for any recent Mediawiki.
> 
> It can write the raw HTML/JS/CSS/PNG... files to the filesystem or pack them all in a highly compressed ZIM file

**Comment by c0nsumer** [comment]
I apologize, I realize I wasn't clear with my question or bug report here.

I'm attempting to figure out if I'm doing something wrong (missing an argument or so), or if this is a bug and mwoffliner isn't behaving as described in the README.md and --help output. It currently _seems_ like a bug.

**Comment by kelson42** [comment]
@c0nsumer Don't apologize because your ticket absolutely legitim. The README.md is misleading and I had to fix it, see https://github.com/openzim/mwoffliner/commit/28203ec052a4dff5b824ca6bdaf95a70151dde4b.

The feature you are expecting was part of MWoffliner but is not part anymore as it became to expensive to maintain. That said, your use case is quite common and we want to provide a solution for that use case. 

First of all, in case you don't have see it, you could use kiwix-serve to directly serve the ZIM file as a Web service. Download binaries here: https://download.kiwix.org/release/kiwix-tools/

But to do what you want, which is unpacking the ZIM file, we recomment to use the `zimdump` binary part of the zim tools. Download binaries for GNU/Linux here: https://download.openzim.org/release/zim-tools/. That said the quality is not really good and we lead an effort (almost finished) currently to have a perfectly working dump2fs feature in zimdump. See for example the PR of https://github.com/openzim/zim-tools/issues?q=is%3Aissue+is%3Aopen+label%3AIPFS. We would really welcome testing on your side.

**Comment by c0nsumer** [comment]
Thank you very much, @kelson42. If I may suggest, maybe update line 17 of cli.ts as well?

Thanks for the idea with kiwix-serve, but my real hope here is to avoid any web app and go to just static. It's just less maintenance and better for long-term archiving. I gave zimdump a go and it seems to be a real good start, but there's some small wrinkles (no file extension for HTML files making mime type identification by a webserver weird) and whatnot. I'll give the zim-tools PRs a look then report things that seem to prevent me from using for this same purpose.

Personally, so long as there's something to archive a MW site to a ZIM file, and then a way to dump the ZIM file to a directory structure to which I can directly point a typical web browser, that'll do exactly what I want.

So, thank you. :)

**Comment by kelson42** [comment]
`zimdump` should be able to dump everything to a directory. Therefore, it should ultimatively do the job for you.

Your point with `.html` is more a problem because the data in the ZIM don't have the `.html` extension. You probably will have to tune your web server to put per default the proper mime-type.

**Comment by c0nsumer** [comment]
Ahh, I wasn't sure if adding those (and I guess modifying the links within the pages) would be within the purview of zimdump or something else.

For what it's worth, I'm working on a .htaccess that'll do the needful and will likely write a blog post covering what's needed. Would it be helpful to have that here as well?

**Comment by kelson42** [comment]
> If I may suggest, maybe update line 17 of cli.ts as well?

It is fixed. Should I close this ticket? An other one could be open of the side of zim-tools if necessary?

**Comment by c0nsumer** [comment]
Please do. :) I found a quirk with zimdump output of images and I'm working on a ticket there. Thanks!
