### ISSUE TITLE
Custom Mainpage is not set properly on the Wiktionary App ZIM file

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1208]
Not sure if this does not work at all or if this is a bug for custom flavour but the custom mainpage configured is not set:
https://farm.openzim.org/pipeline/5f0db890e2aaee5905635ef7

**Comment by bakshiutkarsha** [comment]
My findings:
1. The customMainPage article `Wiktionnaire:Page_d’accueil_hors-ligne` is not filtered by `shouldKeepArticle` method as it doesn't contain `#fr.sectionlangue`. That is the reason why this problem is occurring.
2. CustomMainPage functionality works fine. (Tested on other smaller wiki)

Question:
If customMainPage article is not filtered by the method, what should be the mainpage given in that case?

**Comment by kelson42** [comment]
Like the ticket requires, what ever the filter result, customMainPage should be there.

**Comment by bakshiutkarsha** [comment]
> Like the ticket requires, what ever the filter result, customMainPage should be there.

Thanks for the reply, will add this requirement.
