### ISSUE TITLE
Missing some articles in "wikipedia_en_astronomy_maxi_2020-07.zim"

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1244]
There is no [**Mars 2020**](https://en.wikipedia.org/wiki/Mars_2020), **[Curiosity (rover)](https://en.wikipedia.org/wiki/Curiosity_(rover))** articles in **wikipedia_en_astronomy_maxi_2020-07.zim**.

**Comment by kelson42** [comment]
@Ubuntu-2020 Please make the usual verification before opening a ticket like this. @Popolechien and myself have explain how it happens that an article is selected.

Here:
* https://en.wikipedia.org/wiki/Talk:Mars_2020 is not part of the Astronmy project
* https://en.wikipedia.org/wiki/Talk:Curiosity_(rover) is not part of the Astronomy project either

**Comment by Ubuntu-2020** [comment]
@kelson42 OK, but why in the **wikipedia_en_astronomy_maxi_2020-07.zim** is not included: [**WikiProject Spaceflight**](https://en.wikipedia.org/wiki/Category:WikiProject_Spaceflight)???

**Comment by Ubuntu-2020** [comment]
@kelson42 OK, but why in the **wikipedia_en_astronomy_maxi_2020-07.zim** is not included: [**WikiProject Spaceflight**](https://en.wikipedia.org/wiki/Category:WikiProject_Spaceflight)???

**Comment by Popolechien** [comment]
@Ubuntu-2020 probably because it was not included in the selection to begin with? Simply add a ticket at [wp1_selection_tools](../../wp1_selection_tools/issues) indicating which wikiproject should be included to a given selection (or removed, I recall that we took biographies out of a couple of project to gain space).
