### ISSUE TITLE
Status Code 404 kills mwOffliner

### ISSUE THREAD

**Issue by darkenvy** [openzim/mwoffliner#1372]
mwOffliner quits when it hits the first 404. Reason unknown. No caching of any kind used.

`--adminEmail="info@iiab.me" \
  --articleList="lists/1000000.tsv" \
  --customZimDescription="Top one million Wikipedia articles" \
  --customZimFavicon="https://en.wikipedia.org/static/images/project-logos/enwiki.png" \
  --customZimTitle="Wikipedia Top 1M" --filenamePrefix="wikipedia_en_top_1m" \
  --format="novid:maxi" \
  --mwUrl="https://en.wikipedia.org/" \
  --outputDirectory="output" \
  --zstd \
  --webp \
  2>&1 | tee mwoffliner-log.log`

tail of the log: https://pastebin.com/FTrMRB9S

I should note, this is a new issue. It ran a 100k article just fine. Coming back to the same 100k article list and it fails at the 500-1000th article position.

**Comment by tim-moody** [comment]
We have also seen this problem in the past on 2 out of 3 1M article runs.

**Comment by kelson42** [comment]
Yes, this has been done on purpose, see https://github.com/openzim/mwoffliner/pull/1351.

**Comment by darkenvy** [comment]
Since #1351 kills the process, perhaps a message stating why it halted would be beneficial. I see from #1351 that the end-goal would be to have a percentage tolerance, but having the error message now would help people understand why it is happening now.

**Comment by kelson42** [comment]
@darkenvy I see the error `Error: Request failed with status code 404`.

**Comment by kelson42** [comment]
@darkenvy @tim-moody @MananJethwani But, I believe here something needs to be improved. Actually we have valid scenarios when we should continue, for example when an article has been deleted in the meantime (beetween the article liste setup and the effective scraping). The idea behind #1329 scraping was that if the backend fails to deliver properly, MWoffliner should just stop because this is not going to give a good result. But if the Mediawiki 404, this is not a backend failure. Do you agree?

**Comment by tim-moody** [comment]
400, 404, 500 are all errors that could be tolerated. The 1M EN WP list has more than 3M images, so 0.1% of all these objects is 4000 items, the absence of which in a zim will still produce a very usable piece of content. You could introduce a max_error runtime parameter that accepts no limit or some number. The ability to retry a list of error items would also help.

**Comment by darkenvy** [comment]
I agree that a 404 is not a backend failure.

When I said a error message, I was thinking of something more specific than `Error: Request failed with status code 404`. Saying "error 404" doesn't correlate _why_ mwOffliner failed, just that a resource failed to download. I was left deep-diving into the code and failed to find the correlation. Heck, I assumed it was a bug and not intention.

What about something like: `the backend failed to deliver properly with a status code 404. MWoffliner stopped because it is not going to give a good result`

**Comment by holta** [comment]
> 400, 404, 500 are all errors

As there are many hundreds of each above error:

- Is it the case that 400 and 500 errors (generally) represent flaws in mwoffliner?
- Whereas 404 errors cannot be fully avoided, given MediaWiki is dynamic content?

What would the most actionable error message be, in each case, to tighten/accelerate the debugging loop?

**Comment by tim-moody** [comment]
400 and 500 do not necessarily represent flaws in mwoffliner
400 is just malformed and could be link inside a page

**Comment by holta** [comment]
> What would the most actionable error message be, in each case, to tighten/accelerate the debugging loop?

The reason for the question is: it takes 4 days to uncover each bug, even with heavily optimized hardware and extremely fast Internet (@darkenvy & @tim-moody each cannot move forward, until each subsequent error is surfaced).

This means 7 bugs can be uncovered per month (best case...)

As we have seen over the past month.

(How can we all accelerate this debugging loop — to surface actionable errors earlier — so that months of dedicated volunteers' time is put to far better use?)

> You could introduce a max_error runtime parameter that accepts no limit or some number. The ability to retry a list of error items would also help.

**Comment by kelson42** [comment]
> The 1M EN WP list has more than 3M images, so 0.1% of all these objects is

This patch concerns only article retrieval.

**Comment by kelson42** [comment]
For the moment, here my status:
* The log is clear about what goes wrong. The formating is not great, but this is something I want to improve anyway.
* The real and only problem is that it seems to stops now because `Nonaqueous_titration` and it could (I'm not sure it is) be legitimate to request this article
* Probably we should build-in a *fault tolerant* system, but here it should simply be *accepted* (this is not a backend error).

@MananJethwani who has made the patch on my request and to whom I plan to ask to fix this ticket will have a look in a few days.

**Comment by tim-moody** [comment]
>This patch concerns only article retrieval.

Perhaps, but the title of the ticket imposes no such restriction. The problem is the undesirable user experience of wasting 4 days on a download to see it be arbitrarily killed. That is the problem that needs fixing.

**Comment by darkenvy** [comment]
`"to me, the log is clear about what goes wrong"`.

mwOffliner has a very specific function and ideology on how it should function. It's intent is not always clear. Perhaps the log is clear to you because you have implicit-knowledge of how mwoffliner _should_ work. From the outside looking in, we don't know the intent. We have different ideas on how the software should work (if it wasn't obvious).

So when we get a "404" on a article download, it can be confusing if we don't share the same ideologies. As you mentioned, some people may want this behavior; they might fully understand the error when they see it. 

I still think adding an additional comment would be beneficial: `mwOffliner cannot proceed due to the error above`. For both the lay-person and the developers.
