### ISSUE TITLE
Some statistics and graphs not scraped in WikiMed

### ISSUE THREAD

**Issue by Jaifroid** [openzim/mwoffliner#1408]
Using the latest `wikipedia_en_medicine_app_maxi_2021-03.zim`, some graphs and statistics are not scraped. See article "COVID-19 in Sweden" (screenshot below), but almost every country page for COVID-19 shows the same problem with graphs. Screenshot below shows Sweden page with Kiwix JS rendering on left and Wikipedia Mobile on right. Using DevTools shows the information is simply missing.

![image](https://user-images.githubusercontent.com/4304337/110206380-27dcfe80-7e75-11eb-9ed3-37fbe3ab3e6f.png)

**Comment by Jaifroid** [comment]
Further information: this is a relatively new bug because the graphs **are** shown in `wikipedia_en_medicine_maxi_2021-01.zim`:

![image](https://user-images.githubusercontent.com/4304337/110206649-e64d5300-7e76-11eb-9a0a-bf26e31caa71.png)

**Comment by kelson42** [comment]
This is a known bug, see #1199 which is a kind of duplicate. These are Graphoid pictures. The problem is that beetwen the time the image is detected in an article and the time it is downloaded, usually the umage has disappeared. Looks like as well that Graphoid’ future is client side rendering in js. Not sure we should fix the bug right now.

**Comment by kelson42** [comment]
@MananJethwani Graphoid has been decomisioned in january 2021 so now the question is only, is the resourceLoader js module loaded properly?

**Comment by kelson42** [comment]
Closing as duplicate. We shoukd really updaye/fix this in 1.13.0.
