### ISSUE TITLE
Many problem with javascript and css dependencies

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#145]
After refactor, in ZIM files created with mwoffliner, the js/css dependencies are not loaded properly.

You can see it for example in this page on this demo/testing of the last created WikiMed ZIM file:
http://download.kiwix.org:8080/wikipedia_en_medicine_2017-10/

If you look at the HTML, you will see the lack of stylesheet.

If you look at the HTML source you will see at the end:
```
    <script src="j/js_modules/jsConfigVars"></script>
    <script src="j/js_modules/startup"></script>
<script src="j/js_modules/jquery"></script>
<script src="j/js_modules/mediawiki"></script>
<script src="j/js_modules/site"></script>
<script src="j/js_modules/ext.cite.a11y"></script>
```

These URLS are wrong and give 404 with kiwix-serve if they are asked. I see at least two problems:
* The URLs should include (here too) ".js" at the end
* The link should be "-/j/js_modules/ext.cite.a11y" as the zimwriterfs chooses automatically that ZIM namespace
* In addition if the url should include the necessary number of "../" depending of the depth of the current URL.

It looks like that this does not have been broken everywhere as I can see things like:
```
<link href="../-/s/css_modules/inserted_style_mobile.css">
```

Same problems with the CSS
```
<link href="s/css_modules/ext.cite.a11y" rel="stylesheet" type="text/css">
<link href="s/css_modules/ext.cite.styles" rel="stylesheet" type="text/css">
```

**Comment by kelson42** [comment]
@darkenvy @subbuss ?

**Comment by kelson42** [comment]
Small remark about the system of namespaces. I'm perfectly aware here that this add an level of complexity because this changes the paths and depth of URL - something not easy to deal as the file on the hardisk do not have the namespace. There is a plan to get rid of these (kind of useless meanwhile) namespace for spring 2018. This should make the life of scrapper developers a bit easier. Sorry again for the burden here.

**Comment by subbuss** [comment]
A few quesions:
1. Has this been generated with current master because d964939d421aa7e86ff7cdb83e70e639d8d4e79e fixes the .js issue. If you did, then, I'll check if I am missing this somewhere else.

2. I am looking at https://github.com/openzim/mwoffliner/blob/5affd206485fe259c9ca54ed57fb6bf7c1d6de80/lib/mwoffliner.lib.js#L1751-L1765 before I started the refactor and I see that the script pat is rooted at javascriptDirectory which is not updated in the file after it is intialized at https://github.com/openzim/mwoffliner/blob/5affd206485fe259c9ca54ed57fb6bf7c1d6de80/lib/mwoffliner.lib.js#L358. So, it looks like the previous code was also generating similar urls?

**Comment by kelson42** [comment]
1 - yes
2 - I can not give any fully 100% garanty about pre-refactor version... but the new resourceLoader mockuping has been introduced earlier this year by a contractor and I verified his work... I would be kind of surprised that If I would not have discovered that pb (with the "-" namespace)... That said, this could have happened.

**Comment by kelson42** [comment]
@subbuss So far as I can see you have fixed the bug :)
