### ISSUE TITLE
"Error contacting the Parsoid/RESTBase server (HTTP 503)"

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1454]
```

  | [error] [2021-05-02T07:22:10.564Z] Error downloading article nedomajita Failed to run mwoffliner after [1600s]: { 	"code": "apierror-visualeditor-docserver-http", 	"info": "Error contacting the Parsoid/RESTBase server (HTTP 503)", 	"*": "See https://io.wiktionary.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes." }
-- | --



```

https://farm.openzim.org/pipeline/468cc304594c4cd7fcc4e806/debug

**Comment by kelson42** [comment]
https://farm.openzim.org/pipeline/e38da5aaff2d244a81d3f806/debug

**Comment by MananJethwani** [comment]
@kelson42 the problem is only reproducible when we fetch the whole Wiktionary, and 503 is for service unavailable I couldn't find any argument we could add to avoid this error and asking on discord I received a suggestion to make only one request per second.

here is the endpoint causing the problem -> https://ky.wiktionary.org/w/api.php?action=visualeditor&mobileformat=html&format=json&paction=parse&page=<page_title>
what should we do?

**Comment by kelson42** [comment]
We should open a ticket upstream, we should not get 503 error code.

Why we use this and not the REST API?

**Comment by MananJethwani** [comment]
@kelson42 looks like the rest API was not detected as the main page we use to detect API had redirects, and we have added header `maxRedirects: 0`

**Comment by kelson42** [comment]
ok, we should find a way to fix that

**Comment by kelson42** [comment]
The interdiction of redirects was introduced to avoid us requesting agains the wrong domain name. I guess if we would allow redirect and check that what changes is only the article name. That would be an ecceptable solution... or do you have an other idea?

**Comment by MananJethwani** [comment]
this workaround is completely fine with me....will implement it shortly
