### ISSUE TITLE
English Wikipedia templates

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1474]
What I really admire about Wikipedia is its navigation, which makes it possible to read everything related to the Earth, for example. One way to navigate is through templates, which sadly are not available in the latest English Wikipedia 2021-03 build. 

According to @zimwikiuser, templates were available in older dumps at the time, and have not been accessible since a long time. (https://github.com/openzim/zim-requests/issues/294)

Everyone knows how meaningful they are, so I really recommend making them available again in the next and future dumps!

Templates increase the effectiveness of an article to the maximum level. Take a look at how lucidly instructive it can appear, providing many notable insights into the related article that are drastically difficult to find without templates.

![Screenshot_20210602-150233_Samsung Internet](https://user-images.githubusercontent.com/71934042/120485357-4db26a80-c3b4-11eb-9b09-54b0a8712e97.jpg)
![Screenshot_20210602-150240_Samsung Internet](https://user-images.githubusercontent.com/71934042/120485372-4ee39780-c3b4-11eb-9626-7cc1a655e895.jpg)
![Screenshot_20210602-153227_Samsung Internet](https://user-images.githubusercontent.com/71934042/120489936-4db46980-c3b8-11eb-8199-9d671e4ec051.jpg)
![Screenshot_20210602-153318_Samsung Internet](https://user-images.githubusercontent.com/71934042/120489945-4ee59680-c3b8-11eb-885c-160561d40e3b.jpg)

https://user-images.githubusercontent.com/71934042/124249927-a183b100-db24-11eb-9577-0b0f9089fc81.mp4

I'm a big fan of Kiwix and the idea behind it, I use Kiwix every day. But honestly, Kiwix is somewhat lacking in navigation right now. Templates would fill this gap very well and give you a better overall feeling while browsing through the millions of articles.

**Comment by Inbefortus** [comment]
Using wikipedia_en_wp1-0.7_2009-05.zim (the ZIM file was created in 2011):

https://user-images.githubusercontent.com/71934042/123552828-4e9ea800-d778-11eb-8777-887b946b5e6c.mp4


https://user-images.githubusercontent.com/71934042/123552829-51010200-d778-11eb-9939-652733cfdd64.mp4


https://user-images.githubusercontent.com/71934042/123553093-abe72900-d779-11eb-989f-3619de253d77.mp4


This is how it should always be. For whatever reason, templates are no longer included. 

Without templates, too much useful information is flushed down the toilet. I was going through the original English Wikipedia again today and I really have to say, templates are simply a must. It's so much more fun to go from article to article, and knowledge is much easier to obtain thanks to them. Without them, it's like reading a huge book without an index.

I'm sure everyone would vote for it. It would be a real shame if they are illogically left out of future ZIMs. :(

**Comment by kelson42** [comment]
I don’t have made an in depth analysis, but my guess is that you check with the desktop version, and we scrape the mobile version.

**Comment by Inbefortus** [comment]
> I don’t have made an in depth analysis, but my guess is that you check with the desktop version, and we scrape the mobile version.

I merely don't understand why you guys don't scrape templates anymore. You did it back then likewise, as I evidenced in my post (2018-10 English Wikipedia). Back then, you have done nothing wrong with the involvement of templates, because it has brought us Kiwix users solely enormous advantages. 

Again. Through them, navigation is significantly improved and the educational process of beneficial knowledge is enhanced many times over.

I assume whenever you read my post thoroughly, you will recognize that this should be reconsidered. This would not yield any drawbacks. No more and no less.

**Comment by Inbefortus** [comment]
I take back what I alleged. @Jaifroid brought my attention to https://pwa.kiwix.org

I am quite surprised. When you open 2021-03 English Wikipedia there and adjust the display style to desktop style, templates are viewable:


https://user-images.githubusercontent.com/71934042/124455754-35a28200-dd8a-11eb-89d4-d1d5531700ed.mp4


https://user-images.githubusercontent.com/71934042/124457676-579d0400-dd8c-11eb-9d32-9eb94ede2ad4.mp4


I steadily presumed that they were not embedded. Back when I tested it on the computer (Windows 10), I retained precisely the same results I got with the Android version. But the fact that you simply have to alter one tiny setting is something I wouldn't have fancied.


If you wish, this topic can hereby be closed.

**Comment by knowledge-is-power** [comment]
@Inbefortus Thank You for your last post about pwa. i had been using kiwix desktop application and kiwix chrome extension but never could get templates/table-of-contents in articles even after tinkering with settings (settings doesnt even have desktop/mobile mode option). i have a two year old zim file which i believed did not even contain templates/ToC data - until now! i installed the pwa and set the display to desktop mode just as you said and voila! there they are. this is the first time i have accessed the templates from my zim file in two years!! 

if the desktop application, chrome extension, pwa (with display mode 'auto') are unable to access templates/ToC data, then this is surely a bug and needs to be addressed. even pwa works only with display mode set to 'desktop'.

**Comment by Jaifroid** [comment]
@knowledge-is-power I'm the dev of the PWA version of Kiwix. The reason we don't display the templates in "auto" mode is because auto uses the ZIM archive's native style (in this case, it is the mobile style; in much older ZIMs it is the desktop style). With the mobile style, even on Wikipedia online, the templates / navboxes are hidden. Therefore it is only when you explicitly request desktop style that these templates are revealed by the desktop CSS. I realize this means that some info that some users find important is missing in default display mode, but I'm not sure what could be done about this without deviating from Wikipedia's own styles (mobile = hidden; desktop = displayed).

**Comment by knowledge-is-power** [comment]
@Jaifroid <https://github.com/Jaifroid> ah, now i see the problem. you have
named the setting 'auto' because you are thinking like a developer but to
the end-user the 'auto' setting means something else. for end-user, it
means the kiwix pwa will automatically adjust the display mode by detecting
the device that it is being used on. the 'auto' doesn't specify what it
actually does. so, may be change the 'auto' to 'default' and provide a
popup tooltip that explains what this 'default' does plus mentioning that
current zim archives have native mobile mode. tooltips are very helpful
indeed, its one the reasons for vlc player's popularity, i think tooltips
must be there in every software cuz no one likes to read long help files.
Since you are here, i'd like to mention one other problem in pwa. whenever
i right-click a link (in wikipedia) and select 'open in new window with pwa
kiwix', the new pwa window opens up but doesn't display anything. however,
when i configure the settings such that a new window should open up just by
right-clicking a link, it works fine (i.e. when right-click doesn't open
context menu but straight away open the link in new pwa window). i'd prefer
opening through the context menu instead, so look into it.
There are two suggested improvements which i hope you could implement.
first, ability to open links in tabs within the pwa window itself. second,
ability to bookmark articles. these two features are already available in
kiwix desktop application but it'll be great to have them implemented in
pwa!!

>

**Comment by Jaifroid** [comment]
@knowledge-is-power Thank you for the suggestions. I like the idea of renaming "auto" to "default", and I can certainly add a tooltip explanation of what the user can expect with that setting. I've opened https://github.com/kiwix/kiwix-js-windows/issues/183 for this.

Regarding right-click, it's not possible to patch the existing context menu as far as I know in an html/js app. I did quite a lot of research trying to find a solution for this. I'd have to write my own context menu to replace the default one, and try to simulate the default menu, which wouldn't be very successful.

The only solution I can suggest for now would be to add a small option not to replace right-click. I.e., ctrl-click and long-press (or middle-click if you have a mouse with middle button) would still open the new tab or window, but right-click would open the context menu.

Regarding tabbed browsing, if you open https://pwa.kiwix.org/ in a browser window instead of opening the installed PWA, it will still work offline (if you have previously visited the site in the same browser), and then you can open multiple tabs in the same browser window (make sure the option "Open in new window instead" is off).

Regarding bookmarks, I've opened https://github.com/kiwix/kiwix-js/issues/757 for this sugestion.

Thanks once again.

**Comment by kelson42** [comment]
At this stage, I have no clue what should be done with this ticket honestly. This ticket talks about so many different things that I consider to have no chance to give any proper answer. Will close it.
