### ISSUE TITLE
Info at the top being lacking in the entire German Wikipedia

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1495]
ZIM: 2021-03 German Wikipedia

The little info at the top is completely missing. I haven't spotted it once in any article.

Original German Wikipedia:

![20210712_175330](https://user-images.githubusercontent.com/71934042/125318875-8d1c9100-e33a-11eb-8e58-06d0736c7d66.jpg)

2021-03 German Wikipedia:

![Screenshot_20210712-175341_Kiwix](https://user-images.githubusercontent.com/71934042/125318914-96a5f900-e33a-11eb-9d2c-df275bea080f.jpg)

**Comment by kelson42** [comment]
This is pretty similar to #182, related to the hatnote.

**Comment by kelson42** [comment]
Thre reason why it is not printed is because the banner has the CSS class `noprint`. We remove all nodes with this class. The logic behind is that if this is not usefull printed on a piece of paper, this is probably not usefull for a ZIM as well. Unfortunately this is not that simple and there is a bit of collateral dommanges.

**Comment by Jaifroid** [comment]
Hmm, that does look a bit like a false economy! There is lots of navigational information one wouldn't want to print on a piece of paper (because paper is static), whereas that information is very useful for a dynamic, hyperlinked medium. Perhaps the `noprint` policy should be revisited to find out how much space is being saved by not including this information. I would guess it is less than 0.1% of a typical ZIM, especially if it is all small textual banners.

**Comment by Inbefortus** [comment]
I understand there is a wide range of irrelevant material that doesn't need to be scraped, and `noprint` does a fantastic job of filtering that material out, but hatnotes and succession boxes are quite informative and provide appropriate information for the given article, so this was really unnecessary (IMO). Hatnotes guide you toward interesting articles you didn't even know existed. The same applies for succession boxes, verily convenient, particularly in articles about people. :-)

If the primary goal is to minimize file size, I also believe this makes a very slight difference in size and thus the deprivation of information is not worth it (IMO).
