### ISSUE TITLE
Wrong image scraped instead of correct image

### ISSUE THREAD

**Issue by Inbefortus** [openzim/mwoffliner#1496]
ZIM: 2021-06 and 2021-07 English Wikipedia (Top Articles)

I've ascertained that I've come across the same flawed image in various, but not many, articles. Both 2021-06 and 2021-07 provide the same concern. Instead of the correct image, an irrelevant image is scraped. I think the next big English Wikipedia would be just as afflicted by this.

Affected articles:
https://en.wikipedia.org/wiki/The_Walking_Dead_(TV_series)#Cast_and_characters
https://en.wikipedia.org/wiki/Pizza#Preparation

2021-06 + 2021-07:

![20210715_211535](https://user-images.githubusercontent.com/71934042/125847020-eda1a1ad-dc30-4f1f-87c7-9972fdc5aee3.jpg)

![Screenshot_20210715-211510_Samsung Internet](https://user-images.githubusercontent.com/71934042/125847024-9086681a-310e-4e22-850d-ec2ee3f339df.jpg)

Original English Wikipedia:

![Screenshot_20210715-212530_Samsung Internet](https://user-images.githubusercontent.com/71934042/125847300-3231577f-fcce-47d9-9353-1c6f4485e9aa.jpg)

![Screenshot_20210715-212546_Samsung Internet](https://user-images.githubusercontent.com/71934042/125847303-87c127f1-6733-48b1-84b9-4779b2a275ec.jpg)

**Comment by kelson42** [comment]
Really strange indeed. So far I have checked, does not seem to be a backend problem.

**Comment by kelson42** [comment]
I think I start to understand what could be the problem. Here are the two images which are not properly scraped in the ZIM:
* https://en.wikipedia.org/w/index.php?title=Pizza&oldid=1024629778#/media/File:US_Navy_070406-N-2959L-756_Members_of_USS_Ronald_Reagan_(CVN_76)_First_Class_Association_prepare_and_put_toppings_on_pizzas_in_the_galley_as_part_of_a_special_dinner_prepared_for_the_crew.jpg
* https://en.wikipedia.org/wiki/The_Walking_Dead_(TV_series)#/media/File:Andrew_Lincoln,_Greg_Nicotero,_Norman_Reedus,_Melissa_McBride,_Lennie_James,_Chandler_Riggs,_Jeffrey_Dean_Morgan,_Lauren_Cohan,_Alanna_Masterson_&_Seth_Gilliam_(cropped).jpg

They have really long filenames. @MananJethwani Might that be we have built a limit on picture filename length?

**Comment by MananJethwani** [comment]
@kelson42 the problem lies with the URL we receive sometimes the URL for thumbnails look like this -> 

`https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Andrew_Lincoln%2C_Greg_Nicotero%2C_Norman_Reedus%2C_Melissa_McBride%2C_Lennie_James%2C_Chandler_Riggs%2C_Jeffrey_Dean_Morgan%2C_Lauren_Cohan%2C_Alanna_Masterson_%26_Seth_Gilliam_%28cropped%29.jpg/440px-thumbnail.jpg`

in this case, the part after 440px should be the same as `Andrew_Lincoln%2C_Greg_Nicotero%2C_Norman_Reedus%2C_Melissa_McBride%2C_Lennie_James%2C_Chandler_Riggs%2C_Jeffrey_Dean_Morgan%2C_Lauren_Cohan%2C_Alanna_Masterson_%26_Seth_Gilliam_%28cropped%29.jpg` but due to some reason(maybe done by mediawiki for long URL) the part is thumbnail.jpg and this would be the same for multiple URLs and hence we get multiple URLs with name thumbnail.jpg and it keeps on overwriting the previous image.

**Comment by kelson42** [comment]
@MananJethwani can you please make a PR with an updated unit test.... and then I will fix the regex to pass?
