### ISSUE TITLE
New program: Wiki-ZIM-exchange

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1611]
Most likely this topic was created in the wrong topic, but I do not know where to create it.
I have an idea.
**ZIM** archive **maxi** weighs a lot. The **English Wikipedia-maxi-ZIM** is about **80 GB**.
It is possible that for some users it is difficult to download such an archive regularly.
But there are small archives like **Computers-maxi-ZIM**, **Football-maxi-ZIM**, **Astronomy-maxi-ZIM**, etc.
Such small archives can be downloaded quickly by users.
Thus, the user has a large archive of **80 GB** with slightly outdated articles and several small archives (**Computers-maxi-ZIM**, **Football-maxi-ZIM**, **Astronomy-maxi-ZIM**) with current articles.
Therefore, it is possible to create a program **Wiki-ZIM-exchange** that would replace articles from an outdated 80 GB archive with actual articles from smaller archives.
Of course, the program must determine the language of the articles (en, de, fr, etc.), the completeness of the archives (maxi, nopic, etc) and many other factors.

- True, in small ZIM-archives, not all links to articles are initially active! It is possible to change something in the settings of small ZIM-archives so that they have links to all articles (just a thought).
- And in a large archive, initially all links to articles are active!

There are probably other complications as well.
I just told my idea.
Might be useful.

**Comment by Jaifroid** [comment]
@Ubuntu-2020 While it might be possible to "plug in" a smaller archive so that it is searched first before following a link in the larger archive, it would instantly at least triple the search time in the back-end, if not increase it by an order of magnitude given that the backend would need to load a separate archive, determine if the article is in it, and if it isn't, reload the original archive to show the requested article. While it's a nice idea in principle, in practice it seems unfeasible, due to the fact that there is no way to determine in advance in which archive an article is present...

**Comment by kelson42** [comment]
This is the whole topic of "incremental update". This would be a nice feature indeed. This is a really complex topic we are familiar with since at least 10 years. For the moment this is postponed to long term todo list. I will close the ticket because this has already been treated in a few other tickets and there is nothing we can do on this in a near future.
