### ISSUE TITLE
Wikipedia:Subpages in ZIM Wikipedia files

### ISSUE THREAD

**Issue by Ubuntu-2020** [openzim/mwoffliner#1646]
Please add [Wikipedia:Subpages](https://en.wikipedia.org/wiki/Wikipedia:Subpages) to ZIM Wikipedia files.
I think pages with instructions, such as [Wikipedia:Manual of Style](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style), [Wikipedia:Deletion policy](https://en.wikipedia.org/wiki/Wikipedia:Deletion_policy) or [Wikipedia:Categorization](https://en.wikipedia.org/wiki/Wikipedia:Categorization) and so on, will be useful to readers of ZIM Wikipedia files.

**Comment by kelson42** [comment]
@Ubuntu-2020 I don’t understand how these page shoukd help a reader of wikipedia which is reqdonly. Do you have a few concrete scenarios in mind?

**Comment by Ubuntu-2020** [comment]
@kelson42 Why create ZIM Wikipedia files at all?
Don't think [Wikipedia:Subpages](https://en.wikipedia.org/wiki/Wikipedia:Subpages) weigh too much.
I would compare [these pages](https://en.wikipedia.org/wiki/Wikipedia:Subpages) of the page with the **Help**, which is in many programs.
Also, I would add [Categories](https://github.com/kiwix/kiwix-desktop/issues/812) that are still not in Wikipedia ZIM files.

**Comment by kelson42** [comment]
We don't scrape meta, non-encyclopedic pages, because most of them and there respective content are non needed in an offline context. Without a strong new argument why this should be changed, this will stay like this.

Regarding categories, thete is no discusdion that this is needed... and we have at least one ticket already open for that.
