### ISSUE TITLE
Using Wikipedia APIs mobile-sections endpoint is deprecated

### ISSUE THREAD

**Issue by johngian** [openzim/mwoffliner#1664]
Related to: https://phabricator.wikimedia.org/T319303

It looks like kiwix is using the `mobile-sections` endpoint served by Wikipedia REST API:
https://en.wikipedia.org/api/rest_v1/#/Mobile

This endpoint is considered deprecated and we are working towards sunsetting it.
Instead of `mobile-sections` its suggested to use the page content for mobile and specifically:
https://en.wikipedia.org/api/rest_v1/#/Page%20content/getContent-mobile-html

**Comment by kelson42** [comment]
@johngian Good to know, nee to read more about the rationals behind this. Hopefully the new end-points are not too different.

**Comment by kelson42** [comment]
@johngian It seems the old is deprecated, but I wonder that you recommend to use a new API end-point which is effectively tagged as « experimental » and therefore not productionreqdy!? See https://de.wikipedia.org/api/rest_v1/#/Page%20content/getContent-mobile-html

**Comment by Jaifroid** [comment]
Given some outdated information as reported in #1397 is caused by using the deprecated mobile-sections API, and that this is only going to get more urgent, we need to work out what is needed to make this switch. I don't know these APIs well, but from what I can see, the mobile-sections endpoint produces JSON or something similar, whereas mobile-html produces (evidently) html.

**Comment by Memory383** [comment]
> this is only going to get more urgent.

**Using the deprecated mobile-sections API is a really severe issue.** It is really frustrating for users and editors.

_For example:_

 I have added more than 500 photos in the German Wiktionary this year. Not a single of those photos appear on the .zim version of the Wiktionary. Also, many translations and definitions are missing. _**Every month the issue is worse !**

By the way, @johngian thanks for opening this issue on GitHub. I am the author of the "Bug report" on Phabricator.

**Comment by kelson42** [comment]
for the moment I'm a bit puzzled:
* new endpoint is still experimental
* references link don't work
* I see strange edit icon at the right of each section title

It seems simply not rreally ready to me.

**Comment by Jaifroid** [comment]
@kelson42 It looks like mwoffliner can get the scripts and styles needed for the mobile view by using this part of the API:

https://en.wikipedia.org/api/rest_v1/#/Page%20content/get_page_mobile_html_offline_resources__title___revision_
