### ISSUE TITLE
Broken Wikilinks when baseUrl includes a path

### ISSUE THREAD

**Issue by uriesk** [openzim/mwoffliner#1707]
Wiki on `https://minecraft.fandom.com/de/`
```
--mwUrl=https://minecraft.fandom.com/de --mwApiPath api.php --mwModulePath load.php --adminEmail=example@example.com
```
will result in a ZIM archive with all wikilinks between articles missing.

to follow the code in `src/MediaWiki.ts`:
```js
  public extractPageTitleFromHref(href: any) {
    try {
      //   baseUrl: 'https://minecraft.fandom.com/de/'
      //   webUrl: 'https://minecraft.fandom.com/de/wiki/'
      //   href:  './Title'
      const pathname = new URL(href, this.baseUrl).pathname;
      // pathname: '/de/Title'

      // Local relative URL
      if (href.indexOf('./') === 0) {
        return util.decodeURIComponent(pathname.substr(1));
        // return 'de/Title' <- not a legit Title
      }
```

i propose
```js
  public extractPageTitleFromHref(href: any) {
    try {
      // Local relative URL
      if (href.indexOf('./') === 0) {
        return util.decodeURIComponent(href.substr(2));
      }

      const pathname = new URL(href, this.baseUrl).pathname;

      // Absolute path
      if (pathname.indexOf(this.webUrl.pathname) === 0) {
        return util.decodeURIComponent(pathname.substr(this.webUrl.pathname.length));
      }

```
but i have no idea how your local parsoid links look like that you have to filter out, so you better review that.
Thanks.

**Comment by kelson42** [comment]
@uriesk We have removed local Parsoid. Domyou use and old version of the code?

**Comment by uriesk** [comment]
no, is current code:

https://github.com/openzim/mwoffliner/blob/main/src/MediaWiki.ts
line 180

**Comment by kelson42** [comment]
This code extract (about Parsoid) is deprecated and should be removed. For some reason it has been forgotten.

**Comment by uriesk** [comment]
then i guess the whole function can be

```js
  public extractPageTitleFromHref(href: any) {
    try {
      // Local relative URL
      if (href.indexOf('./') === 0) {
        return util.decodeURIComponent(href.substr(2));
      }

      const pathname = new URL(href, this.baseUrl).pathname;

      // Absolute path
      if (pathname.indexOf(this.webUrl.pathname) === 0) {
        return util.decodeURIComponent(pathname.substr(this.webUrl.pathname.length));
      }

      return null; /* Interwiki link? -- return null */
    } catch (error) {
      logger.warn(`Unable to parse href ${href}`);
      return null;
    }
  }
```

btw. (different topic) i would appreciate it if you could review my latest push request

**Comment by kelson42** [comment]
@uriesk IMO the problem is probably wrong values for MWoffliner arguments or in worse case a really strange configuration at Fandom.

After looking a bit to the HTML and your ticket description, it seems to me that the base `mwUrl` should be https://minecraft.fandom.com/ (without `/de/`). The other values shoudl be changed accordingly.

This is what I have done on the Zimfarm. We will see the result.

**Comment by uriesk** [comment]
Nice, should work,
but it might bite you in the future that the `new URL(href, this.baseUrl)` produces an invalid path.
Years from now, the future you, might have to look at this for some other reason and be confused about it.
```js
  public extractPageTitleFromHref(href: any) {
    try {
      //   baseUrl: 'https://minecraft.fandom.com/'
      //   webUrl: 'https://minecraft.fandom.com/de/wiki/'
      //   href:  './Title'
      const pathname = new URL(href, this.baseUrl).pathname;
      // url: 'https://minecraft.fandom.com/Title' <- weird
      // pathname: '/Title'

      // Local relative URL
      if (href.indexOf('./') === 0) {
        return util.decodeURIComponent(pathname.substr(1));
        // return 'Title' <- good
      }
```

**Comment by kelson42** [comment]
@uriesk Last run has been successful, see https://farm.openzim.org/pipeline/a83a1c88aca15ced59d45b36. From the article perspective, it looks good, but all the image links are broken. It seems somehow the webp URL rewrite fails (because the images are in the ZIM)... probably because it expects a picture file extension in the URL, but fandom somehow (because of CDN probably) as a pretty custom URL scheme (for example https://static.wikia.nocookie.net/minecraft_de_gamepedia/images/9/96/Hauptseite_Minecraft_Legends.png/revision/latest/scale-to-width-down/80?cb=20220627163221). This is probably pretty easy to fix, but please open another ticket so we can avoid mixing discussions.

**Comment by uriesk** [comment]
The images themselves or links when you click on images?
I checked out the zimfarm build and all images besides some gifs aren't showing.

The images are not broken in my build where i did it like described in OP.

**Comment by uriesk** [comment]
I will add that to my pull request #1706 and rebase.

I see no reason why anyone needs to add the baseUrl to an relative link just to cut it off again to get an article title.
Tell me if you disagree and want to have it reverted again.

**Comment by kelson42** [comment]
@uriesk Lets try first to get the ZIM working, then we can discuss if changing a few things is a good idea to improve MWoffliner. 

The problem is not with the pictures, but with the links to the pictures in the HTML. You don't have used the `--webp` option probably, this explains why you don't have the problem. We use it meanwhile to all our ZIM files because this allows to significantly reduce the size of the ZIM.

Please don't fix two different problem with the same PR.

**Comment by uriesk** [comment]
meh, i don't see a reason for discussing for three lines of code or so :)
Lets leave it
