### ISSUE TITLE
Automated landing page does not pick obvious winners

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1786]
The 1M top selection's welcome page (see https://library.kiwix.org/viewer#wikipedia_en_top1m_maxi) shows a number of unexpected entries, e.g. Maggie Hassan, Mexican Beaded Lizard, Nikolai Rizhkov, etc.). In fact, I could not find any that was listed in the common lists of popular wikipedia articles.

Possible solutions: 
- Hard code list from the [most popular pages of all time](Wikipedia:Popular_pages)
- Use the [monthly pageviews ranking](https://pageviews.wmcloud.org/topviews/?project=en.wikipedia.org&platform=all-access&date=last-month&excludes=)

**Comment by kelson42** [comment]
@pavel-karatsiuba The articles presented on the welcome page shoukd be important article. In other terms they should the first ib the list given as selection here: https://download.openzim.org/wp1/enwiki/tops/1000000.tsv. Whole recipe is here https://farm.openzim.org/recipes/wikipedia_en_top1m.

Here is seems to take random articles of the list instead of the first ones... looks we have a regression!

**Comment by holta** [comment]
> they should be the first in the list given as selection here: https://download.openzim.org/wp1/enwiki/tops/1000000.tsv

Just FYI the top 100 articles' graphics would indeed have been used if February 2021's PR had been merged here:

- PR #1399

But a different approach was chosen for some reason:

- PR #1490

**Comment by kelson42** [comment]
@holta Communication problems as usual. I was confused and actually still I'm by rereading your PR comments. I was not smart enough (and probably too much to do as well) to rearticulate all of this in a manner I could have dealt with it properly. Respecting https://github.com/openzim/overview/wiki/Report-a-bug would have helped and this is what I requested in my first comment.
