### ISSUE TITLE
Search result returns text with formatting code

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1797]
Tested both on Kiwix-server and Kiwix-android, not sure this is the right place but here we go:

Looked at Wikispecies ([2023-02](https://library.kiwix.org/viewer#wikispecies_en_all_maxi_2023-02/A/Main_Page)) and searched for _Terminalia chebula_. Because this is a plant species name in latin, it is displayed in italics.

I get the following results with the `<i> </i>` in the search bar:
- on Kiwix-server
![Capture d’écran 2023-02-27 à 10 20 04](https://user-images.githubusercontent.com/21675885/221526580-36077f48-628a-4d75-8bda-dcfa77f2b981.png)
- on Kiwix-android
![Screenshot_20230227-101807](https://user-images.githubusercontent.com/21675885/221526709-a1dd668c-9655-40fc-bbbe-57ba0950c6a1.png)

**Comment by kelson42** [comment]
@Popolechien Indeed, probably a bug in MWoffliner. Actually we had this very symptom in the past already (still need to find the ticket), therefore looks almost like a regression to me.
@pavel-karatsiuba Can you please tell us what is going on here with this article?

**Comment by pavel-karatsiuba** [comment]
By specification, the title tag must be text-only. But for some reason title contains tags.
I have added a patch to strip tags from the title.

**Comment by kelson42** [comment]
@pavel-karatsiuba Make sense, I will check upstream if I can find a ticket.

**Comment by kelson42** [comment]
At the source this is a bug in Mediawiki, reported here https://phabricator.wikimedia.org/T331120

**Comment by Jaifroid** [comment]
The corresponding article in Wikipedia has the title of the article in italics, but the search entry isn't showing `<i>` either in Kiwix Serve or in Kiwix JS.

It's important not to strip out legitimate search characters. For example, `&lt` is a legitimate search term for a Wikipedia article, yielding an article on the `Less than` sign `<`. There is a Directory Entry with a `dirEntry.url` that is simply `&lt` (see screenshot). This mustn't be stripped. It is a correct and intentional search term on Wikipedia.

![image](https://user-images.githubusercontent.com/4304337/236662712-3949aa0e-9a36-4ec6-af59-3e8422500abe.png)

![image](https://user-images.githubusercontent.com/4304337/236662848-c48bfa78-b3a5-43b6-9183-224905d2cc58.png)

**Comment by kelson42** [comment]
@Jaifroid Pretty sure this is a duplicate

**Comment by Jaifroid** [comment]
Just adding info from the duplicate issue, because this is a recurrence or regression, though caused by the API, not mwoffliner. Might need a workaround?

> I'm not sure if this is fixed by #1872 or not, but I noticed in `wikipedia_en_movies_maxi_2023-09.zim` (which is missing article titles in the article HTML), that the directory entry title field has accidentally scraped HTML. See the dirEntry for `Blade Runner (film)` below.
>
> ![image](https://github.com/openzim/mwoffliner/assets/4304337/9e1d44c6-097e-4766-a7fd-4cec57dba39c)
>
> Clearly, the spec says titles should not be URL-encoded, but in fact the directory entry title shouldn't have any HTML at all in it, AFAIK.
>
> I've seen this also in a simple Ray Charles ZIM too.

**Comment by kelson42** [comment]
Now tracked at https://phabricator.wikimedia.org/T324431

**Comment by kelson42** [comment]
It seems the upstream bug has been fixed, https://phabricator.wikimedia.org/T324431. It should be verified

**Comment by kelson42** [comment]
<img width="1080" alt="Image" src="https://github.com/user-attachments/assets/53fb3a6f-546d-4bbe-bbeb-96ec922b20e7" />
