### ISSUE TITLE
"Unable to find appropriate API end-point to retrieve article HTML"

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1857]
The recipe for [dico des ados](https://farm.openzim.org/recipes/dicoado) has been failing for a while now, and returns this unusual message. Does this mean that the issue is on their end (and what problem resolution could we suggest)?

**Comment by DSwissK** [comment]
Hello, the api URL is wrong, this is the right one : https://fr.dicoado.org/w/api.php

Here are some other changes I can see :
favicon : https://fr.dicoado.org/w/images/thumb/0/04/Favicon.svg/1920px-Favicon.svg
mwModulePath : /w/load.php
mwUrl : https://fr.dicoado.org/
mwWikiPath : /w/index.php

Thanks !

**Comment by kelson42** [comment]
I will fix the recipe if confirmed its wrong. Key point is that visual editor api has to be available.

**Comment by DSwissK** [comment]
Looks like it's available. Example with "baleine" : https://fr.dicoado.org/w/api.php?action=visualeditor&page=baleine&paction=parse

**Comment by kelson42** [comment]
Seems to work now, see https://farm.openzim.org/recipes/dicoado

**Comment by gitubbi** [comment]
Last run has again failed 5 minutes ago.

**Comment by DSwissK** [comment]
Last run suceeded, thanks !

**Comment by Popolechien** [comment]
Yeah well the scraping worked _but_ looking at https://dev.library.kiwix.org/viewer#dicoado_fr_all_maxi_2023-07 :  
1. Categories on the front page are not working (though I think this is a feature on mwoffliner's part and could be fixed maybe) and 
2. Images are missing:
![Capture d’écran 2023-07-06 à 11 14 26](https://github.com/openzim/mwoffliner/assets/21675885/e96cadc3-4e09-47a6-9a4f-af3342f1b137)

@kelson42 should we open separate tickets ?

**Comment by DSwissK** [comment]
I don't know if you changed anything since yesterday but when I go to https://dev.library.kiwix.org/viewer#dicoado_fr_all_maxi_2023-07/A/chablon I can see the images :
<img width="679" alt="image" src="https://github.com/openzim/mwoffliner/assets/22744090/b1350ad1-98d9-4fd6-973c-1be6c717582d">

The categories on the front page aren't working though. And the layout is a bit strange (all these "::" and "[[" "]]", maybe related to Semantic MediaWiki (SMW) extension)
