### ISSUE TITLE
wikipedia_de_all failing since March 2023

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1861]
See https://farm.openzim.org/recipes/wikipedia_de_all

**Comment by Inbefortus** [comment]
It has been failing, particularly since the addition of addNamespaces (portals). 
The most recent run backfired with `Request failed with status code 504: Error downloading article Portal:Biologie/Fehlende_Artikel/Missing_Topics`. It could just be a coincidence, but I'm convinced it's related.

I would just remove addNamespaces and give it another shot. If that's not enough, there is evidently a more serious matter at hand...

**Comment by Popolechien** [comment]
@Inbefortus Thanks, I just gave it a shot. @RavanJAltaie can you please keep an eye on it and have a look in a few days time?

**Comment by Inbefortus** [comment]
@Popolechien It [failed](https://farm.openzim.org/pipeline/0658d73d-dd2a-4753-b6ae-88521dd6047a) yet again, but this time for different reasons: `Unable to retrieve js/css dependencies for article 'Holomorphe Funktion': internal_api_error_Wikimedia\RequestTimeout\RequestTimeoutException`

I've witnessed this on other large wikis, and AFAIK the `requestTimeout=300` parameter resolved it(?). This parameter already exists on DE Wikipedia, so this is odd. Perhaps raise the timeout and/or begin the scraping with one of the MWOffliner workers? Pixelmemory, athena18, and michaelblob have a tendency to fail with greater regularity than the rest.

**Comment by Popolechien** [comment]
@Inbefortus Someone has started working on fixing mwoffliner, let's keep this ticket as a benchmark of things to look at.

**Comment by Inbefortus** [comment]
@Popolechien I have good news: there is a fresh DE Wikipedia [ZIM](https://farm.openzim.org/pipeline/25903968-3fb5-4ab9-ae18-d4cc05c950fe) file available for download 😃. I'm sure the removal of addNamespaces helped, as did the fact that the worker who completed the task was mwoffliner2!

**Comment by Popolechien** [comment]
Schön. Merci viel mal ^^
