### ISSUE TITLE
Make URLs exactly the same as online

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#278]
For example, currently we have this kind of URL:
```
http://library.kiwix.org/wikipedia_fr_all_novid_2018-03/A/Potentiel_thermodynamique.html
```

The corresponding orignal URL looks like:
```
https://fr.wikipedia.org/wiki/Potentiel_thermodynamique
```

We should provide:
```
http://library.kiwix.org/wikipedia_fr_all_novid_2018-03/Potentiel_thermodynamique
```

The point of the additional namespace `A` will be treated https://github.com/openzim/libzim/issues/15, so this ticket is not about that.

This ticket is (at least) about:
* Removing the trailing ".html" extension
* Stop replacing the character `/` with `_`
* Maybe other changes I'm not aware of.

**Comment by ISNIT0** [comment]
- Trailing `.html`. I believe this is down to Kiwix-serve
- `/` -> `_` This will affect everything the reads ZIM files - it's impossible to have `/` characters in file names or directory names

**Comment by kelson42** [comment]
@ISNIT0 If Kiwix-serve needs to be adapted, it will. for the fs, maybe it should not be written to the filesystem ;) (or then a solution should be found...)

**Comment by kelson42** [comment]
@ISNIT0 The goal of this this ticket is to have an easy and automatic way, from a online WP url to figure out the ZIM local url, and the other way around. This is necessary to be able to implement feature like: if at some point you have an online Wikipedia URL but the device is offline, automatically switch to Kiwix to read from the ZIM file. Currently to many transformation are done on the ZIM URLs to allow to do that easily.

So far, I know the `.html` extensions are created within `mwoffliner`. Regarding the problem with the `/`, why not creating subdirectories with `mwoffliner` instead of attempting to re-encode the `/` within a filename?

**Comment by ISNIT0** [comment]
Thanks for the clarification.
I'll change mwoffliner to create sub-directories for files. (I assume all zim readers will cope?)

**Comment by kelson42** [comment]
@ISNIT0 They should

**Comment by ISNIT0** [comment]
I've found an issue here.

If we create directories rather than encoding `/` characters, we would break this kind of page: `https://fr.wikipedia.org/wiki//dev/random`

The page starts with a `/`. Notice that neither of these two urls point to the same page:
- `https://fr.wikipedia.org/wiki/dev/random` (With one of the slash characters removed)
- `https://fr.wikipedia.org/wiki///dev/random` (With an extra slash)

I think these changes you've suggested should be implemented in `kiwix-serve` which would translate the MediaWiki like urls into the Zim paths.

Kiwix Serve Should:
- Strip `.html` from urls and dynamically add it when looking on the file-system
- Convert `/` characters into `_` characters

Does this make sense? I just think it would cause various issues if we stopped encoding `/` characters in file names. It's possible I've mis-understood what you mean again in which case we should have a Skype call.

**Comment by kelson42** [comment]
@ISNIT0 Any ZIM reader should be stupid. We need a ZIM file with a URL like `/dev/random/` or to be more precise (and as long as we do not have removed the namespaces) 'A//dev/random/`.

**Comment by kelson42** [comment]
@ISNIT0 If I correctly understand the technical problem, the difficulty is to deal with both limitation of Mediawiki and Filesystem charsets. On thing we could do, is move this ticket to milestone 1.8. That way, one time we use less the filesystem to store things, maybe the problem will be easier to solve.

**Comment by ISNIT0** [comment]
I think we should have a call about this particular issue, I think what you're asking here is not technically possible with a Unix filesystem (how do you represent `A//dev` in a filesystem)

**Comment by ISNIT0** [comment]
This will be implemented as part of #184 where we're not restricted by filesystems

**Comment by kelson42** [comment]
@ISNIT0 Have you been able to make progresses on this? Does this ticket still need clarification?

**Comment by ISNIT0** [comment]
@kelson42 I have all the clarification I need, thanks. This will be relatively easy to implement soon
