### ISSUE TITLE
zim of Encyclopedia of Life

### ISSUE THREAD

**Issue by amirh123123** [openzim/mwoffliner#330]
hi please make zim file for Encyclopedia of Life
eol.org

**Comment by darkenvy** [comment]
Pleas see https://github.com/openzim/mwoffliner/issues/331 for the same answer :)

**Comment by darkenvy** [comment]
" In short, all information you share with EOL must also be shared with the rest of the world under at least one of the creative commons licenses that allow re-use."

Turns out to be CC and okay for reuse. This site is heavily fragmented. Is there a particular part of the site you are interested in? Like the education section located at http://eol.org/discover ? Are you still interested in this?

_discliamer: If Im able to rip this, its something I would be doing myself and not something the openzim team would be expected to do._

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#12
