### ISSUE TITLE
Remove Dekstop rendering

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#395]
Go mobile and secure it works well - on non-mobile devices too.

**Comment by ISNIT0** [comment]
@bradyhunsaker Your favourite :)

**Comment by Jaifroid** [comment]
I just add a slight note of caution: let's not lose sight of the fact that some of the larger ZIMs are not very feasible on mobile, and will be accessed almost exclusively on desktop/laptop machines, where the desktop style is more readable. I note that the default style on Wikipedia is still desktop, not mobile... 

But, if this is done, please can #164, #182 and #110 be fixed first? I'm particularly keen on #164 (missing MathJax info) being fixed, because it is a tangible loss of information in mobile style that cannot be worked around.

Philosophically, in an ideal world, it seems to me that the ZIM should supply the raw information, and the client should take charge of the display mode, according to user preference or screen size. This would be like the idea behind XHTML or HTML5, that there is a separation between information (the XML/HTML) and styling (CSS), with the styling being transformable. But I realize that may not be technically feasible at this point in time.

**Comment by kelson42** [comment]
@Jaifroid What I want is only one rendering, based on the Mediawiki `MobileView` and somehow adapted to also fix as much as possible the Desktop viewer. In the past, we had "desktop first" and now we have "mobile first". @ISNIT0 #164 is really important but I suspect a bug on Parsoid side, would be really great to fix it or report in on Wikimedia side properly.

**Comment by Jaifroid** [comment]
@kelson42 OK that makes sense. It is possible to transform the MobileView to Desktop and vice versa -- I do this in Kiwix JS Windows (if user requests it). But the Desktop-style CSS would need to be available for the client to extract from the ZIM when the transform is requested. It could be done with a custom `inserted_style_desktop` CSS file (like the custom `inserted_style_mobile` that we currently use in mobile-style ZIMs). There are some other transforms that are needed to move the infoboxes, etc., up from their mobile position to the top of the page. But it's not too hard, and can easily be implemented in clients.

**Comment by kelson42** [comment]
@Jaifroid So far we have tried to have only one stylesheet. If this is not substainable, then we will make it part of the future JS API, so readers can easily deal with it.
