### ISSUE TITLE
Wikivoyage: Tapping on map marker number unhandled

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#494]
_From @ARR8 on January 8, 2019 16:2_

App version: Wikivoyage 2018-12
Android version: 9, no Google Play Services

The markers are also always numbered 1.  
See error at bottom of image
![screenshot_20190108-105902_wikivoyage](https://user-images.githubusercontent.com/8064135/50842431-93db7f00-135e-11e9-915d-5776def0fae4.png)

_Copied from original issue: kiwix/kiwix-android-custom#25_

**Comment by Jaifroid** [comment]
The problem here is that either the client or the OS doesn't know what to do with geo: links. These links are part of the vCard schema. We had an issue in Kiwix JS which supported these: see [Make vCard geo: and tel: URIs work](https://github.com/kiwix/kiwix-js/issues/313). However, I don't think this is an mwoffliner issue. The links are correct in the source html, so it's up to the client to interpret them correctly and launch them as required by the OS. In Kiwix JS Windows, I have to transform these geo: links so that they launch the offline Windows Maps app.

**Comment by ARR8** [comment]
You're right, the problem's on my end, thanks. Safe to close the issue.

**Comment by ARR8** [comment]
Er, not quite. Maybe the issue with the marker numbers not iterating or being visible should be spun off.

**Comment by Jaifroid** [comment]
Numerical markers only make sense if you have a map represented in the app. Then they are used to mark specific places on the map. In Kiwix JS Windows, I simply transform these to unnumbered map pins, as shown in the screenshot. The screenshot shows these map pins in the app on the right, and one of them opened in the Maps App on the left. When clicking on a map pin, the system app should open centred on the geolocation co-ordinates. The description for the location is taken from the vCard data.

![image](https://user-images.githubusercontent.com/4304337/50982865-0e8ad280-14f6-11e9-8d1d-67acda1b31fb.png)

**Comment by kelson42** [comment]
@Jaifroid We handle the numbering label problem separatly here #871. I would be in favour to just replace is with a logo, for example: https://www.compart.com/en/unicode/U+1F30D
