### ISSUE TITLE
Disambiguation or "Main article" links do not appear in eswp/nopic

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#60]
Both are templates and not images, so that's a bit weird.

See images for Cataluna on Wikipedia
![capture d ecran 2017-04-20 a 12 03 36](https://cloud.githubusercontent.com/assets/21675885/25225354/6abee7a6-25c1-11e7-93dc-fb032374a1cd.png)

and the eswp/nopic zim:
![capture d ecran 2017-04-20 a 12 04 32](https://cloud.githubusercontent.com/assets/21675885/25225391/87fe6058-25c1-11e7-8965-d1f9b260f5ce.png)

**Comment by kelson42** [comment]
Here is how the HTML looks like

`<div class="noprint AP rellink"><span style="font-size:88%">Artículo principal:</span> <i><a href="/wiki/Historia_de_Catalu%C3%B1a" title="Historia de Cataluña">Historia de Cataluña</a></i></div>`

The  important part is the "noprint" CSS class.

Here we have two problems:
* mwoffliner has a hard-coded blacklist of CSS classes. The idea behind is to remove any content which should not have any sense in an offline content. For good or bad reasons, the "nopic" class belongs to that list.
* This list is hard-coded, which means that it applies on all wikis in the same way.

In general, this is a good idea to remove the DOM element with this class because if the WP contributors think a content has no value if the page is printed, probably it has no value in a ZIM file eather.

We probably needs something smarter, but it's not clear to me which logic should be implemented instead.

An idea maybe, we have also a list which is "cssClassBlackListIfNoLink", maybe "nopic" should be put there instead?

**Comment by Popolechien** [comment]
@kelson42 would it make sense to alter the template's coding directly?

**Comment by kelson42** [comment]
@Popolechien Too politic... I prefer we find ways on our side without having to deal with communities.
