### ISSUE TITLE
ZIM file made with 1.8.6 has a lot of broken images (image in article but not available)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#723]
See https://download.kiwix.org/zim/wikipedia/wikipedia_ps_all_novid_2019-05.zim

**Comment by ISNIT0** [comment]
The images don't seem to even be downloaded

**Comment by ISNIT0** [comment]
Can't reproduce this locally on master...

**Comment by kelson42** [comment]
@ISNIT0 Please secure that the app retries and stop if the data can not be downloaded.

**Comment by ISNIT0** [comment]
@kelson42 Why should it stop? In the past when MWO stops when it can't get content we've agreed it should continue... It was a bug to stop

**Comment by kelson42** [comment]
@ISNIT0 What do you propose to stop producing Wikipedia ZIM with missing images?

**Comment by ISNIT0** [comment]
@kelson42 I'm adding a scrape summary log at the end of a "successful" scrape e.g.:

```
[log] [2019-05-18T13:27:21.879Z] Summary of scrape actions: {
	"files": {
		"success": 1002,
		"fail": 1
	},
	"articles": {
		"success": 729,
		"fail": 0
	},
	"redirects": {
		"written": 186
	}
}
``` 
This should help us with checking the scrapes went okay.
Perhaps we could set a threshold of failed downloads that's acceptable? I don't think it makes sense to stop all scraping because of a single missing image though.

**Comment by kelson42** [comment]
@ISNIT0 Thx, I kind of agree that it does not make sense to stop everything. The problem is that if we don't put a high price on not scrapping things properly then we won't never fix the problem (and this problem is not new). The fundamental problem here is that the retry mechanism seems to fail to overcome temporary network problems: we don't retry enough or not a the right moment or we don't check properly... How does it works currently? How many times we retry content download before abandoning and what is the delay between each retry? How do we identify that a download is a success or not?

**Comment by ISNIT0** [comment]
I completely agree that we should have a high bar for quality of the ZIM files.
The current retry logic will retry 5 times, with an exponential backoff (https://github.com/MathieuTurcotte/node-backoff#backoffexponentialoptions), so the first retry will be 100ms since the first request, and the last one will be 11500ms since the first request. The download is considered a failure if all 5 requests fail.

It would be nice to have more of an insight into why the requests fail - do they come as a 404, or something else? This data is all logged, but we only keep a subset of the logs.
Seeing as we can't keep all the logs to do meaningful analysis, it might be worth integrating some kind of full analytics integration.

**Comment by kelson42** [comment]
@ISNIT0 Yes, we need the full log. Meanwhile, could you do something to just increase a lot the time between two retries? I think if the last retry could happen 30 mn later (or at the end of the scrapping) that would be really better?
