### ISSUE TITLE
Inciclopedia welcome page is missing links (made with 1.8.6)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#729]
in https://download.kiwix.org/zim/other/inciclopedia_es_all_2019-05.zim

The text "American Graffiti" on the welcome page should be a link pointing to the article "American Graffiti" (like [here online](https://inciclopedia.org/w/index.php?title=Inciclopedia:Portada&oldid=1526359)) but instead this is just a text. The article "American Graffiti" exists in the ZIM file, so this is really strange.

**Comment by ISNIT0** [comment]
Couldn't reproduce this with articleList, trying a full scrape now

**Comment by kelson42** [comment]
@ISNIT0 Here was my command line https://github.com/openzim/zim-requests/issues/101#issuecomment-491519948

**Comment by pyroshroom** [comment]
There is a similar issue with the English Wikivoyage homepage in https://download.kiwix.org/zim/wikivoyage/wikivoyage_en_all_novid_2019-06.zim where the "North America" and "South America" links on the home page at https://en.wikivoyage.org/wiki/Wikivoyage:Offline_reader_Expedition/Home_page are also regular text instead of a link. The pages "North America" and "South America" also still exist within that .zim file.

**Comment by pyroshroom** [comment]
Found the issue again on the English RationalWiki main page (https://rationalwiki.org/wiki/Main_Page) where the Portals and Articles section of the main page is missing tons of links to pages that are still present in the zim files. (Even the templates on other pages are missing links)

This issue is present in:
https://download.kiwix.org/zim/other/rationalwiki_en_all_novid_2019-05.zim
https://download.kiwix.org/zim/other/rationalwiki_en_all_novid_2019-06.zim

**Comment by kelson42** [comment]
@ISNIT0 Please have a look in priority to this problem. This is a seriously spread problem.

**Comment by ISNIT0** [comment]
The commonality seems to be that all broken links have spaces in them. Will look at this now

**Comment by kelson42** [comment]
We have new scrapes, with 1.9.4, of both Inciclopedia & Wikivoyage. It should really be fixed now hopefully.
