### ISSUE TITLE
If only one section and smal screen width, then the section should not be collapsed

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#838]
Uh just to be clear - a user just complained that top-level section titles were collapsed by default (and it's hard to disagree with him). Am I right to understand that this will be corrected to a wikipedia-like mobile view?
![comparaison](https://user-images.githubusercontent.com/21675885/59604636-02dab200-910d-11e9-96db-4a048296761b.jpg)
@kelson42 's to be honest I'm not sure I even understand the issue you described, as expanded top-level sections and collapsed everything below that seems to be the correct approach :-/

https://github.com/openzim/mwoffliner/issues/786#issuecomment-502667450

**Comment by kelson42** [comment]
@Popolechien In your screenshot, this is not the top-level section which is collapsed, this is the first paragraph... and this is the normal behaviour: all paragraphs are collapsed if screen width is "small". I have checked with https://de.m.wiktionary.org/wiki/Franse and in that case it is true that online the first paragraph is open.

**Comment by vaibhavmatta** [comment]
If not resolved, May I start resolving this one?

**Comment by kelson42** [comment]
@vaibhavmatta Yes! Thank you! I suspect here the solution might be quite trivial.

**Comment by vaibhavmatta** [comment]
Thanks.! I am working on it now and will give my best in resolving this issue.

**Comment by vaibhavmatta** [comment]
Can you please tell me the exact file to work on? I think I am missing something here.
Thanks

**Comment by ISNIT0** [comment]
@vaibhavmatta This is the line that opens all sections: https://github.com/openzim/mwoffliner/blob/master/res/script.js#L16

The file is in `/res/`. No processing is done to the script file, it's just copied and referenced directly within the ZIM file. (So it needs to be valid ES5 syntax)

**Comment by vaibhavmatta** [comment]
Will event.stopPropagation() help here? 
Like, we can stop the default action and the titles won't collapse.

**Comment by ISNIT0** [comment]
@vaibhavmatta The sections are supposed to collapse.
The logic should be something along the lines of:

```javascript
var levelTwoDetails = $('details[data-level=2]');
var isMobile = window.innerWidth < 720
if (!isMobile || levelTwoDetails.length === 1) {
    levelTwoDetails.attr('open', true);
}
```

**Comment by vaibhavmatta** [comment]
Yes that's what I am saying. I think I am on correct path. I will try and get back to you If I face any problem. Thanks

**Comment by vaibhavmatta** [comment]
@ISNIT0 Can you please guide me how to run the app/project on Local Server.
I've gone through the source code. Thanks

**Comment by kelson42** [comment]
@vaibhavmatta Everything is in the README/CONTRIBUTING files. What is exactly your question?

**Comment by vaibhavmatta** [comment]
I went through Readme again. Doubt solved. 
Thanks for such supporting behavior.

**Comment by ISNIT0** [comment]
@vaibhavmatta Have you managed to run the scraper yet?

**Comment by vaibhavmatta** [comment]
Yes Sir..! I ll send a PR by tomorrow morning for sure..! 😊

**Comment by vaibhavmatta** [comment]
@ISNIT0 I am still working on this issue.

**Comment by vaibhavmatta** [comment]
@ISNIT0  Sir, I'm not able to run the app in my local. Please help me. I'm Stuck. Being new, I dont know how to start the local server for this app. I've followed all the instructions given in the contribute and readme.md file.

**Comment by kelson42** [comment]
@vaibhavmatta mwoffliner is not a server. Which server are talking about?

**Comment by vaibhavmatta** [comment]
@kelson42 , I am asking about how to run mwoffliner on my local? how can I check the changes made in the code?

**Comment by vaibhavmatta** [comment]
@ISNIT0 Any help?

**Comment by kelson42** [comment]
@vaibhavmatta you can run it against wikipedia.org for example

**Comment by vaibhavmatta** [comment]
<img width="471" alt="Screenshot 2019-08-07 at 2 05 21 AM" src="https://user-images.githubusercontent.com/50797619/62699025-2c70d500-b9fc-11e9-8f2e-ca5fa16a5754.png">
what to write in the place of adminEmail=XXX ?

**Comment by vaibhavmatta** [comment]
<img width="930" alt="Screenshot 2019-08-08 at 4 46 48 PM" src="https://user-images.githubusercontent.com/50797619/62699187-98533d80-b9fc-11e9-93ce-aa2a344fe746.png">

What to write for adminEmail=XXX?

**Comment by kelson42** [comment]
@vaibhavmatta Your email address. The scraper user-agent will take it.

**Comment by kelson42** [comment]
@vaibhavmatta news?

**Comment by vaibhavmatta** [comment]
@kelson42 My Laptop's OS got corrupted. It will be back by tomorrow and I will make a PR asap.

**Comment by Jaifroid** [comment]
I think I have a useful observation that could be part of the PR and is probably related. If it turns out not to be related I'll open it as a separate issue.

Looking at `wikipedia_en_history_maxi_2019-08.zim`, there is **inconsistency in the application of the `open` attribute on the `details` tag**. Details corresponding to an `h3`, or `h4` tag have the `open` attribute in the source html, but sections corresponding to an `h2` tag have no `open` attribute. For clients that do not run any included JavaScript (and cannot do so), it results in what you see in the screenshots below. This is problematic because, for example, endnotes won't work if the corresponding references section is closed. It also seems very odd to have top-level sections closed while more detailed sections are open.

Here also is sample HTML from the same page to show the issue in code. **The solution is simply ensuring that `details` sections corresponding to `h2` tags have the `open` attribute.**

HTML (unprocessed source html as extracted from above ZIM, with cuts at `...` ):
```
<details data-level="3" open="">
    <summary class="section-heading"><h3 id="In_popular_culture">In popular culture</h3></summary>
<div class="thumb tright">.
    ...
</details>

<details data-level="2">
    <summary class="section-heading"><h2 id="See_also">See also</h2></summary>
<div class="div-col columns column-width" style="-moz-column-width: 18em; -webkit-column-width: 18em; column-width: 18em;   ">
    ...
</details><details data-level="2">
    <summary class="section-heading"><h2 id="Notes">Notes</h2></summary>
    ...
```
Screenshots on clients that do not process JavaScript (Kiwix JS in jQuery mode):

![image](https://user-images.githubusercontent.com/4304337/63222762-cde9ea80-c1a3-11e9-8667-223344b96c03.png)

![image](https://user-images.githubusercontent.com/4304337/63222768-e1955100-c1a3-11e9-8fcd-a63255d735ad.png)

**Comment by ISNIT0** [comment]
@Jaifroid Do I understand correctly:
All sections should be open by default, and then javascript can be used to collapse sections if necessary?

**Comment by vaibhavmatta** [comment]
@ISNIT0 Yes! This is exactly what is required.

**Comment by kelson42** [comment]
@ISNIT0 @vaibhavmatta @Jaifroid From a user perspective it should work like the online version... If someone want to do something different please open a different ticket. @Jaifroid Please open an other ticket, one problem = one ticket is a gold rule.

**Comment by Jaifroid** [comment]
@kelson42 I can open a specific issue for the missing `open` attributes. It seemed to me that it's very closely related to the problem reported in this issue, but I agree that this issue is a specific case of the broader problem.

@ISNIT0, indeed it would be much better if all sections were open in the raw HTML, and then JS closes those required to mimic the behaviour of Wikipedia online mobile site, as @kelson42 says. It means that clients that do not process JS-in-the-ZIM would not have difficulties.

**Comment by kelson42** [comment]
Looks like its not clear how the online stuff works: everything open if not mobile screen, otherwise collapsed. If only one section, then it works differently... this is the topic of this ticket.
