### ISSUE TITLE
Allow images to be used by multiple zims

### ISSUE THREAD

**Issue by ChristianKurz** [openzim/mwoffliner#944]
Many images in different langugae versions of wikipedia are actually stored at wikimedia commons. 

It would be nice for mwoffliner to detect wikimedia commons files and save a link, instead of downloading them.

A separate zim file containing all (compressed) commons images could be made available. These images would be linked from the wikipedia zims.

Apart from reducing space requirements and download times, several flavours of image zims could be offered: 
- all images, maximum compression (~30gb?)
- hd images for those with big sd-cards
- only the top 100.000 images, in high resolution
- separate zim for video & audio files
- if no image-zim is present, default to online images

On the other hand, images won't be updated as often as text. One could choose to update the text-only zims every second month, but to never update images.

What would be needed to accomplish this?

**Comment by kelson42** [comment]
This is the kind of idea which might look theoritically good, but in fact not working because:
* By doing so, even for the top5 Wikipedia, many users have only one language and will end-up downloading far more than necessary
* The bundle would be over 100GB and I'm not even couting with high res
* Really complicated to handle
* ...

Not a good idea. Sorry.
